name: veter_app
description: "Veter - Local-first E2EE Corporate Messenger"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.2
  
  # Networking and HTTP
  http: ^1.2.2
  
  # Local storage
  sqflite: ^2.4.0
  shared_preferences: ^2.3.2
  
  # Crypto and security
  crypto: ^3.0.5
  
  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0
  
  # File handling
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Permissions
  permission_handler: ^11.3.1
  
  # Notifications
  flutter_local_notifications: ^17.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
